name: multirtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python==3.13.5
  - boto3
  - burst2safe
  - gdal>=3.0
  - geojson
  - geopandas
  - hyp3lib>=3,<4
  - isce3
  - lxml
  - numpy>=1.20
  - pip
  - pyproj
  - pystac-client
  - rasterio
  - requests
  - requests
  - s1reader>=0.2.5
  - sarpy
  - shapely
  - tqdm
  - urllib3
  # For multimetric
  - lmfit
  - matplotlib
  - pandas
  - scikit-image
  - scipy
  # For packaging, and testing
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ruff
  - setuptools
  - setuptools_scm
  - wheel
